### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by vitormicillo** [staempfli/magento2-module-pdf#2]
Hi Guys,
sorry for my dumb question, but how do you use your component to generate PDFs from orders?
Thanks

**Comment by mhauri** [comment]
Hi @vitormicillo thank you for pointing out that this module lacks in documentation.
We try to add a useful doc as soon as we work again on the Module. In the meantime you can read an article written by @schmengler where he explains how to use it.

https://www.schmengler-se.de/en/2016/12/pdf-generation-in-magento-2/

If you have further questions you're welcome to ask.

**Comment by jalogut** [comment]
Hi @vitormicillo `Readme.md` has been updated with the corresponding documentation
